# Generated by Django 5.0.6 on 2024-07-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('ward', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/')),
            ],
        ),
    ]
