# Generated by Django 5.0.6 on 2024-07-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='feedback',
        ),
    ]
