# Generated by Django 5.0.6 on 2024-07-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_content_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='content',
        ),
    ]
