# Generated by Django 5.0.6 on 2024-07-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_issue_reporter_issue_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='reported_by',
        ),
    ]
