# Generated by Django 5.0.6 on 2024-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
