# Generated by Django 5.0.6 on 2024-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_issue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Water & Sanitation', 'Water & Sanitation'), ('Fires', 'Fires'), ('Children & Minors', 'Children & Minors'), ('Electricity & Power', 'Electricity & Power'), ('Criminal Activities', 'Criminal Activities'), ('Roads & Infrastructure', 'Roads & Infrastructure')], default='Health', max_length=50),
        ),
    ]
